# Generated by Django 4.0.6 on 2022-08-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_remove_patientinfo_author_alter_patientinfo_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
