# Generated by Django 4.0.6 on 2022-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True, blank=True),
        ),
    ]
