# Generated by Django 4.0.6 on 2022-09-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0007_alter_patientinfo_gender_registeredpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
