# Generated by Django 4.0.6 on 2022-09-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0008_patientinfo_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='patient_id',
            new_name='ssn',
        ),
    ]
